# Generated by Django 3.1 on 2020-11-04 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='payload',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_payload', message='Message must be Alphanumeric or must have any of these special char({}$%_-/~@#$%^&*()!?)', regex='^[a-zA-Z0-9\\{\\}$%_\\-\\/~@#$%^&*()!?]*$')]),
        ),
    ]
