# Generated by Django 3.1 on 2020-11-05 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_auto_20201104_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='payload',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_payload', message='Message must be Alphanumeric or must have any of these special char({}$%_-/~@#$%^&*()!?)', regex='^[a-zA-Z0-9\\{\\}$%_\\-\\/~@#$%^&*()!? ]*$')]),
        ),
        migrations.CreateModel(
            name='ScheduleChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_chats', to='conversation.chat')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_chats', to='conversation.conversation')),
            ],
        ),
    ]
